server {
  listen 8080;
  server_name 44.203.209.74;

  root /usr/share/nginx/html;
  index index.html;

  location /api/ventas/ {
    proxy_pass http://10.0.8.79:8080/api/v1/ventas/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /api/despachos/ {
    proxy_pass http://10.0.8.139:8081/api/v1/despachos/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
